#!/bin/sh
case "$1" in
  start)
        echo "Starting custom Python OS script..."
        python3 /usr/bin/init.py &
        ;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
